// Generated by `scripts/generate_android_domain_model.py` on 2019-12-07 14:53:49
// using Zotero domain model downloaded on 2019-12-07 00:08:57.

@file:Suppress("unused", "UNUSED_PARAMETER")

package net.tomasfiers.zoro.data

open class ItemMixin {
    var abstractNote: String? = null
    var accessDate: String? = null
    var applicationNumber: String? = null
    var archive: String? = null
    var archiveLocation: String? = null
    var artworkMedium: String? = null
    var artworkSize: String? = null
    var assignee: String? = null
    var audioFileType: String? = null
    var audioRecordingFormat: String? = null
    var billNumber: String? = null
    var blogTitle: String? = null
    var bookTitle: String? = null
    var callNumber: String? = null
    var caseName: String? = null
    var code: String? = null
    var codeNumber: String? = null
    var codePages: String? = null
    var codeVolume: String? = null
    var committee: String? = null
    var company: String? = null
    var conferenceName: String? = null
    var country: String? = null
    var court: String? = null
    var date: String? = null
    var dateDecided: String? = null
    var dateEnacted: String? = null
    var dictionaryTitle: String? = null
    var distributor: String? = null
    var docketNumber: String? = null
    var documentNumber: String? = null
    var DOI: String? = null
    var edition: String? = null
    var encyclopediaTitle: String? = null
    var episodeNumber: String? = null
    var extra: String? = null
    var filingDate: String? = null
    var firstPage: String? = null
    var forumTitle: String? = null
    var genre: String? = null
    var history: String? = null
    var institution: String? = null
    var interviewMedium: String? = null
    var ISBN: String? = null
    var ISSN: String? = null
    var issue: String? = null
    var issueDate: String? = null
    var issuingAuthority: String? = null
    var itemType: String? = null
    var journalAbbreviation: String? = null
    var label: String? = null
    var language: String? = null
    var legalStatus: String? = null
    var legislativeBody: String? = null
    var letterType: String? = null
    var libraryCatalog: String? = null
    var manuscriptType: String? = null
    var mapType: String? = null
    var meetingName: String? = null
    var nameOfAct: String? = null
    var network: String? = null
    var note: String? = null
    var numberOfVolumes: String? = null
    var numPages: String? = null
    var pages: String? = null
    var patentNumber: String? = null
    var place: String? = null
    var postType: String? = null
    var presentationType: String? = null
    var priorityNumbers: String? = null
    var proceedingsTitle: String? = null
    var programmingLanguage: String? = null
    var programTitle: String? = null
    var publicationTitle: String? = null
    var publicLawNumber: String? = null
    var publisher: String? = null
    var references: String? = null
    var reporter: String? = null
    var reporterVolume: String? = null
    var reportNumber: String? = null
    var reportType: String? = null
    var rights: String? = null
    var runningTime: String? = null
    var scale: String? = null
    var section: String? = null
    var series: String? = null
    var seriesNumber: String? = null
    var seriesText: String? = null
    var seriesTitle: String? = null
    var session: String? = null
    var shortTitle: String? = null
    var studio: String? = null
    var subject: String? = null
    var system: String? = null
    var thesisType: String? = null
    var title: String? = null
    var university: String? = null
    var url: String? = null
    var versionNumber: String? = null
    var videoRecordingFormat: String? = null
    var volume: String? = null
    var websiteTitle: String? = null
    var websiteType: String? = null
}

enum class ItemType(camelCaseName: String, friendlyName: String) {
    ARTWORK("artwork", "Artwork"),
    ATTACHMENT("attachment", "Attachment"),
    AUDIO_RECORDING("audioRecording", "Audio Recording"),
    BILL("bill", "Bill"),
    BLOG_POST("blogPost", "Blog Post"),
    BOOK("book", "Book"),
    BOOK_SECTION("bookSection", "Book Section"),
    CASE("case", "Case"),
    COMPUTER_PROGRAM("computerProgram", "Computer Program"),
    CONFERENCE_PAPER("conferencePaper", "Conference Paper"),
    DICTIONARY_ENTRY("dictionaryEntry", "Dictionary Entry"),
    DOCUMENT("document", "Document"),
    EMAIL("email", "E-mail"),
    ENCYCLOPEDIA_ARTICLE("encyclopediaArticle", "Encyclopedia Article"),
    FILM("film", "Film"),
    FORUM_POST("forumPost", "Forum Post"),
    HEARING("hearing", "Hearing"),
    INSTANT_MESSAGE("instantMessage", "Instant Message"),
    INTERVIEW("interview", "Interview"),
    JOURNAL_ARTICLE("journalArticle", "Journal Article"),
    LETTER("letter", "Letter"),
    MAGAZINE_ARTICLE("magazineArticle", "Magazine Article"),
    MANUSCRIPT("manuscript", "Manuscript"),
    MAP("map", "Map"),
    NEWSPAPER_ARTICLE("newspaperArticle", "Newspaper Article"),
    NOTE("note", "Note"),
    PATENT("patent", "Patent"),
    PODCAST("podcast", "Podcast"),
    PRESENTATION("presentation", "Presentation"),
    RADIO_BROADCAST("radioBroadcast", "Radio Broadcast"),
    REPORT("report", "Report"),
    STATUTE("statute", "Statute"),
    THESIS("thesis", "Thesis"),
    TV_BROADCAST("tvBroadcast", "TV Broadcast"),
    VIDEO_RECORDING("videoRecording", "Video Recording"),
    WEBPAGE("webpage", "Web Page")
}

enum class Field(camelCaseName: String, friendlyName: String) {
    ABSTRACT_NOTE("abstractNote", "Abstract"),
    ACCESS_DATE("accessDate", "Accessed"),
    APPLICATION_NUMBER("applicationNumber", "Application Number"),
    ARCHIVE("archive", "Archive"),
    ARCHIVE_LOCATION("archiveLocation", "Loc. in Archive"),
    ARTWORK_MEDIUM("artworkMedium", "Medium"),
    ARTWORK_SIZE("artworkSize", "Artwork Size"),
    ASSIGNEE("assignee", "Assignee"),
    AUDIO_FILE_TYPE("audioFileType", "File Type"),
    AUDIO_RECORDING_FORMAT("audioRecordingFormat", "Format"),
    BILL_NUMBER("billNumber", "Bill Number"),
    BLOG_TITLE("blogTitle", "Blog Title"),
    BOOK_TITLE("bookTitle", "Book Title"),
    CALL_NUMBER("callNumber", "Call Number"),
    CASE_NAME("caseName", "Case Name"),
    CODE("code", "Code"),
    CODE_NUMBER("codeNumber", "Code Number"),
    CODE_PAGES("codePages", "Code Pages"),
    CODE_VOLUME("codeVolume", "Code Volume"),
    COMMITTEE("committee", "Committee"),
    COMPANY("company", "Company"),
    CONFERENCE_NAME("conferenceName", "Conference Name"),
    COUNTRY("country", "Country"),
    COURT("court", "Court"),
    DATE("date", "Date"),
    DATE_ADDED("dateAdded", "Date Added"),
    DATE_DECIDED("dateDecided", "Date Decided"),
    DATE_ENACTED("dateEnacted", "Date Enacted"),
    DATE_MODIFIED("dateModified", "Modified"),
    DICTIONARY_TITLE("dictionaryTitle", "Dictionary Title"),
    DISTRIBUTOR("distributor", "Distributor"),
    DOCKET_NUMBER("docketNumber", "Docket Number"),
    DOCUMENT_NUMBER("documentNumber", "Document Number"),
    DOI("DOI", "DOI"),
    EDITION("edition", "Edition"),
    ENCYCLOPEDIA_TITLE("encyclopediaTitle", "Encyclopedia Title"),
    EPISODE_NUMBER("episodeNumber", "Episode Number"),
    EXTRA("extra", "Extra"),
    FILING_DATE("filingDate", "Filing Date"),
    FIRST_PAGE("firstPage", "First Page"),
    FORUM_TITLE("forumTitle", "Forum/Listserv Title"),
    GENRE("genre", "Genre"),
    HISTORY("history", "History"),
    INSTITUTION("institution", "Institution"),
    INTERVIEW_MEDIUM("interviewMedium", "Medium"),
    ISBN("ISBN", "ISBN"),
    ISSN("ISSN", "ISSN"),
    ISSUE("issue", "Issue"),
    ISSUE_DATE("issueDate", "Issue Date"),
    ISSUING_AUTHORITY("issuingAuthority", "Issuing Authority"),
    ITEM_TYPE("itemType", "Item Type"),
    JOURNAL_ABBREVIATION("journalAbbreviation", "Journal Abbr"),
    LABEL("label", "Label"),
    LANGUAGE("language", "Language"),
    LEGAL_STATUS("legalStatus", "Legal Status"),
    LEGISLATIVE_BODY("legislativeBody", "Legislative Body"),
    LETTER_TYPE("letterType", "Type"),
    LIBRARY_CATALOG("libraryCatalog", "Library Catalog"),
    MANUSCRIPT_TYPE("manuscriptType", "Type"),
    MAP_TYPE("mapType", "Type"),
    MEETING_NAME("meetingName", "Meeting Name"),
    NAME_OF_ACT("nameOfAct", "Name of Act"),
    NETWORK("network", "Network"),
    NUMBER_OF_VOLUMES("numberOfVolumes", "# of Volumes"),
    NUM_PAGES("numPages", "# of Pages"),
    PAGES("pages", "Pages"),
    PATENT_NUMBER("patentNumber", "Patent Number"),
    PLACE("place", "Place"),
    POST_TYPE("postType", "Post Type"),
    PRESENTATION_TYPE("presentationType", "Type"),
    PRIORITY_NUMBERS("priorityNumbers", "Priority Numbers"),
    PROCEEDINGS_TITLE("proceedingsTitle", "Proceedings Title"),
    PROGRAMMING_LANGUAGE("programmingLanguage", "Language"),
    PROGRAM_TITLE("programTitle", "Program Title"),
    PUBLICATION_TITLE("publicationTitle", "Publication"),
    PUBLIC_LAW_NUMBER("publicLawNumber", "Public Law Number"),
    PUBLISHER("publisher", "Publisher"),
    REFERENCES("references", "References"),
    REPORTER("reporter", "Reporter"),
    REPORTER_VOLUME("reporterVolume", "Reporter Volume"),
    REPORT_NUMBER("reportNumber", "Report Number"),
    REPORT_TYPE("reportType", "Report Type"),
    RIGHTS("rights", "Rights"),
    RUNNING_TIME("runningTime", "Running Time"),
    SCALE("scale", "Scale"),
    SECTION("section", "Section"),
    SERIES("series", "Series"),
    SERIES_NUMBER("seriesNumber", "Series Number"),
    SERIES_TEXT("seriesText", "Series Text"),
    SERIES_TITLE("seriesTitle", "Series Title"),
    SESSION("session", "Session"),
    SHORT_TITLE("shortTitle", "Short Title"),
    STUDIO("studio", "Studio"),
    SUBJECT("subject", "Subject"),
    SYSTEM("system", "System"),
    THESIS_TYPE("thesisType", "Type"),
    TITLE("title", "Title"),
    UNIVERSITY("university", "University"),
    URL("url", "URL"),
    VERSION_NUMBER("versionNumber", "Version"),
    VIDEO_RECORDING_FORMAT("videoRecordingFormat", "Format"),
    VOLUME("volume", "Volume"),
    WEBSITE_TITLE("websiteTitle", "Website Title"),
    WEBSITE_TYPE("websiteType", "Website Type")
}

enum class CreatorType(camelCaseName: String, friendlyName: String, itemType: ItemType) {
    ARTWORK_ARTIST("artist", "Artist", ItemType.ARTWORK),
    ARTWORK_CONTRIBUTOR("contributor", "Contributor", ItemType.ARTWORK),
    AUDIO_RECORDING_COMPOSER("composer", "Composer", ItemType.AUDIO_RECORDING),
    AUDIO_RECORDING_CONTRIBUTOR("contributor", "Contributor", ItemType.AUDIO_RECORDING),
    AUDIO_RECORDING_PERFORMER("performer", "Performer", ItemType.AUDIO_RECORDING),
    AUDIO_RECORDING_WORDS_BY("wordsBy", "Words By", ItemType.AUDIO_RECORDING),
    BILL_CONTRIBUTOR("contributor", "Contributor", ItemType.BILL),
    BILL_COSPONSOR("cosponsor", "Cosponsor", ItemType.BILL),
    BILL_SPONSOR("sponsor", "Sponsor", ItemType.BILL),
    BLOG_POST_AUTHOR("author", "Author", ItemType.BLOG_POST),
    BLOG_POST_COMMENTER("commenter", "Commenter", ItemType.BLOG_POST),
    BLOG_POST_CONTRIBUTOR("contributor", "Contributor", ItemType.BLOG_POST),
    BOOK_AUTHOR("author", "Author", ItemType.BOOK),
    BOOK_CONTRIBUTOR("contributor", "Contributor", ItemType.BOOK),
    BOOK_EDITOR("editor", "Editor", ItemType.BOOK),
    BOOK_SECTION_AUTHOR("author", "Author", ItemType.BOOK_SECTION),
    BOOK_SECTION_BOOK_AUTHOR("bookAuthor", "Book Author", ItemType.BOOK_SECTION),
    BOOK_SECTION_CONTRIBUTOR("contributor", "Contributor", ItemType.BOOK_SECTION),
    BOOK_SECTION_EDITOR("editor", "Editor", ItemType.BOOK_SECTION),
    BOOK_SECTION_SERIES_EDITOR("seriesEditor", "Series Editor", ItemType.BOOK_SECTION),
    BOOK_SECTION_TRANSLATOR("translator", "Translator", ItemType.BOOK_SECTION),
    BOOK_SERIES_EDITOR("seriesEditor", "Series Editor", ItemType.BOOK),
    BOOK_TRANSLATOR("translator", "Translator", ItemType.BOOK),
    CASE_AUTHOR("author", "Author", ItemType.CASE),
    CASE_CONTRIBUTOR("contributor", "Contributor", ItemType.CASE),
    CASE_COUNSEL("counsel", "Counsel", ItemType.CASE),
    COMPUTER_PROGRAM_CONTRIBUTOR("contributor", "Contributor", ItemType.COMPUTER_PROGRAM),
    COMPUTER_PROGRAM_PROGRAMMER("programmer", "Programmer", ItemType.COMPUTER_PROGRAM),
    CONFERENCE_PAPER_AUTHOR("author", "Author", ItemType.CONFERENCE_PAPER),
    CONFERENCE_PAPER_CONTRIBUTOR("contributor", "Contributor", ItemType.CONFERENCE_PAPER),
    CONFERENCE_PAPER_EDITOR("editor", "Editor", ItemType.CONFERENCE_PAPER),
    CONFERENCE_PAPER_SERIES_EDITOR("seriesEditor", "Series Editor", ItemType.CONFERENCE_PAPER),
    CONFERENCE_PAPER_TRANSLATOR("translator", "Translator", ItemType.CONFERENCE_PAPER),
    DICTIONARY_ENTRY_AUTHOR("author", "Author", ItemType.DICTIONARY_ENTRY),
    DICTIONARY_ENTRY_CONTRIBUTOR("contributor", "Contributor", ItemType.DICTIONARY_ENTRY),
    DICTIONARY_ENTRY_EDITOR("editor", "Editor", ItemType.DICTIONARY_ENTRY),
    DICTIONARY_ENTRY_SERIES_EDITOR("seriesEditor", "Series Editor", ItemType.DICTIONARY_ENTRY),
    DICTIONARY_ENTRY_TRANSLATOR("translator", "Translator", ItemType.DICTIONARY_ENTRY),
    DOCUMENT_AUTHOR("author", "Author", ItemType.DOCUMENT),
    DOCUMENT_CONTRIBUTOR("contributor", "Contributor", ItemType.DOCUMENT),
    DOCUMENT_EDITOR("editor", "Editor", ItemType.DOCUMENT),
    DOCUMENT_REVIEWED_AUTHOR("reviewedAuthor", "Reviewed Author", ItemType.DOCUMENT),
    DOCUMENT_TRANSLATOR("translator", "Translator", ItemType.DOCUMENT),
    EMAIL_AUTHOR("author", "Author", ItemType.EMAIL),
    EMAIL_CONTRIBUTOR("contributor", "Contributor", ItemType.EMAIL),
    EMAIL_RECIPIENT("recipient", "Recipient", ItemType.EMAIL),
    ENCYCLOPEDIA_ARTICLE_AUTHOR("author", "Author", ItemType.ENCYCLOPEDIA_ARTICLE),
    ENCYCLOPEDIA_ARTICLE_CONTRIBUTOR("contributor", "Contributor", ItemType.ENCYCLOPEDIA_ARTICLE),
    ENCYCLOPEDIA_ARTICLE_EDITOR("editor", "Editor", ItemType.ENCYCLOPEDIA_ARTICLE),
    ENCYCLOPEDIA_ARTICLE_SERIES_EDITOR("seriesEditor", "Series Editor", ItemType.ENCYCLOPEDIA_ARTICLE),
    ENCYCLOPEDIA_ARTICLE_TRANSLATOR("translator", "Translator", ItemType.ENCYCLOPEDIA_ARTICLE),
    FILM_CONTRIBUTOR("contributor", "Contributor", ItemType.FILM),
    FILM_DIRECTOR("director", "Director", ItemType.FILM),
    FILM_PRODUCER("producer", "Producer", ItemType.FILM),
    FILM_SCRIPTWRITER("scriptwriter", "Scriptwriter", ItemType.FILM),
    FORUM_POST_AUTHOR("author", "Author", ItemType.FORUM_POST),
    FORUM_POST_CONTRIBUTOR("contributor", "Contributor", ItemType.FORUM_POST),
    HEARING_CONTRIBUTOR("contributor", "Contributor", ItemType.HEARING),
    INSTANT_MESSAGE_AUTHOR("author", "Author", ItemType.INSTANT_MESSAGE),
    INSTANT_MESSAGE_CONTRIBUTOR("contributor", "Contributor", ItemType.INSTANT_MESSAGE),
    INSTANT_MESSAGE_RECIPIENT("recipient", "Recipient", ItemType.INSTANT_MESSAGE),
    INTERVIEW_CONTRIBUTOR("contributor", "Contributor", ItemType.INTERVIEW),
    INTERVIEW_INTERVIEWEE("interviewee", "Interview With", ItemType.INTERVIEW),
    INTERVIEW_INTERVIEWER("interviewer", "Interviewer", ItemType.INTERVIEW),
    INTERVIEW_TRANSLATOR("translator", "Translator", ItemType.INTERVIEW),
    JOURNAL_ARTICLE_AUTHOR("author", "Author", ItemType.JOURNAL_ARTICLE),
    JOURNAL_ARTICLE_CONTRIBUTOR("contributor", "Contributor", ItemType.JOURNAL_ARTICLE),
    JOURNAL_ARTICLE_EDITOR("editor", "Editor", ItemType.JOURNAL_ARTICLE),
    JOURNAL_ARTICLE_REVIEWED_AUTHOR("reviewedAuthor", "Reviewed Author", ItemType.JOURNAL_ARTICLE),
    JOURNAL_ARTICLE_TRANSLATOR("translator", "Translator", ItemType.JOURNAL_ARTICLE),
    LETTER_AUTHOR("author", "Author", ItemType.LETTER),
    LETTER_CONTRIBUTOR("contributor", "Contributor", ItemType.LETTER),
    LETTER_RECIPIENT("recipient", "Recipient", ItemType.LETTER),
    MAGAZINE_ARTICLE_AUTHOR("author", "Author", ItemType.MAGAZINE_ARTICLE),
    MAGAZINE_ARTICLE_CONTRIBUTOR("contributor", "Contributor", ItemType.MAGAZINE_ARTICLE),
    MAGAZINE_ARTICLE_REVIEWED_AUTHOR("reviewedAuthor", "Reviewed Author", ItemType.MAGAZINE_ARTICLE),
    MAGAZINE_ARTICLE_TRANSLATOR("translator", "Translator", ItemType.MAGAZINE_ARTICLE),
    MANUSCRIPT_AUTHOR("author", "Author", ItemType.MANUSCRIPT),
    MANUSCRIPT_CONTRIBUTOR("contributor", "Contributor", ItemType.MANUSCRIPT),
    MANUSCRIPT_TRANSLATOR("translator", "Translator", ItemType.MANUSCRIPT),
    MAP_CARTOGRAPHER("cartographer", "Cartographer", ItemType.MAP),
    MAP_CONTRIBUTOR("contributor", "Contributor", ItemType.MAP),
    MAP_SERIES_EDITOR("seriesEditor", "Series Editor", ItemType.MAP),
    NEWSPAPER_ARTICLE_AUTHOR("author", "Author", ItemType.NEWSPAPER_ARTICLE),
    NEWSPAPER_ARTICLE_CONTRIBUTOR("contributor", "Contributor", ItemType.NEWSPAPER_ARTICLE),
    NEWSPAPER_ARTICLE_REVIEWED_AUTHOR("reviewedAuthor", "Reviewed Author", ItemType.NEWSPAPER_ARTICLE),
    NEWSPAPER_ARTICLE_TRANSLATOR("translator", "Translator", ItemType.NEWSPAPER_ARTICLE),
    PATENT_ATTORNEY_AGENT("attorneyAgent", "Attorney/Agent", ItemType.PATENT),
    PATENT_CONTRIBUTOR("contributor", "Contributor", ItemType.PATENT),
    PATENT_INVENTOR("inventor", "Inventor", ItemType.PATENT),
    PODCAST_CONTRIBUTOR("contributor", "Contributor", ItemType.PODCAST),
    PODCAST_GUEST("guest", "Guest", ItemType.PODCAST),
    PODCAST_PODCASTER("podcaster", "Podcaster", ItemType.PODCAST),
    PRESENTATION_CONTRIBUTOR("contributor", "Contributor", ItemType.PRESENTATION),
    PRESENTATION_PRESENTER("presenter", "Presenter", ItemType.PRESENTATION),
    RADIO_BROADCAST_CAST_MEMBER("castMember", "Cast Member", ItemType.RADIO_BROADCAST),
    RADIO_BROADCAST_CONTRIBUTOR("contributor", "Contributor", ItemType.RADIO_BROADCAST),
    RADIO_BROADCAST_DIRECTOR("director", "Director", ItemType.RADIO_BROADCAST),
    RADIO_BROADCAST_GUEST("guest", "Guest", ItemType.RADIO_BROADCAST),
    RADIO_BROADCAST_PRODUCER("producer", "Producer", ItemType.RADIO_BROADCAST),
    RADIO_BROADCAST_SCRIPTWRITER("scriptwriter", "Scriptwriter", ItemType.RADIO_BROADCAST),
    REPORT_AUTHOR("author", "Author", ItemType.REPORT),
    REPORT_CONTRIBUTOR("contributor", "Contributor", ItemType.REPORT),
    REPORT_SERIES_EDITOR("seriesEditor", "Series Editor", ItemType.REPORT),
    REPORT_TRANSLATOR("translator", "Translator", ItemType.REPORT),
    STATUTE_AUTHOR("author", "Author", ItemType.STATUTE),
    STATUTE_CONTRIBUTOR("contributor", "Contributor", ItemType.STATUTE),
    THESIS_AUTHOR("author", "Author", ItemType.THESIS),
    THESIS_CONTRIBUTOR("contributor", "Contributor", ItemType.THESIS),
    TV_BROADCAST_CAST_MEMBER("castMember", "Cast Member", ItemType.TV_BROADCAST),
    TV_BROADCAST_CONTRIBUTOR("contributor", "Contributor", ItemType.TV_BROADCAST),
    TV_BROADCAST_DIRECTOR("director", "Director", ItemType.TV_BROADCAST),
    TV_BROADCAST_GUEST("guest", "Guest", ItemType.TV_BROADCAST),
    TV_BROADCAST_PRODUCER("producer", "Producer", ItemType.TV_BROADCAST),
    TV_BROADCAST_SCRIPTWRITER("scriptwriter", "Scriptwriter", ItemType.TV_BROADCAST),
    VIDEO_RECORDING_CAST_MEMBER("castMember", "Cast Member", ItemType.VIDEO_RECORDING),
    VIDEO_RECORDING_CONTRIBUTOR("contributor", "Contributor", ItemType.VIDEO_RECORDING),
    VIDEO_RECORDING_DIRECTOR("director", "Director", ItemType.VIDEO_RECORDING),
    VIDEO_RECORDING_PRODUCER("producer", "Producer", ItemType.VIDEO_RECORDING),
    VIDEO_RECORDING_SCRIPTWRITER("scriptwriter", "Scriptwriter", ItemType.VIDEO_RECORDING),
    WEBPAGE_AUTHOR("author", "Author", ItemType.WEBPAGE),
    WEBPAGE_CONTRIBUTOR("contributor", "Contributor", ItemType.WEBPAGE),
    WEBPAGE_TRANSLATOR("translator", "Translator", ItemType.WEBPAGE)
}
